version: '3'
services:
  fibonacci-java:
    build: ./
    ports:
      - "8081:8080"
    environment:
      OTEL_SERVICE_NAME: "fibonacci-java"
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=6d1331ab-cfd3-4fff-9dfe-21e5cbfab49a
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=${NEW_RELIC_API_KEY}"
      OTEL_EXPORTER_OTLP_COMPRESSION: gzip
      OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT: 1000